# Generated by Django 4.2.13 on 2024-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('desc', models.CharField(max_length=300, unique=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
