# Generated by Django 4.2.13 on 2024-06-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='home_image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_1',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_2',
            field=models.ImageField(default='Image/None/Noimf.jpg', upload_to='Image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_3',
            field=models.ImageField(default='Image/None/Noimf.jpg', upload_to='Image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_4',
            field=models.ImageField(default='Image/None/Noimf.jpg', upload_to='Image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_5',
            field=models.ImageField(default='Image/None/Noimf.jpg', upload_to='Image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image_6',
            field=models.ImageField(default='Image/None/Noimf.jpg', upload_to='Image/'),
        ),
    ]
