# Generated by Django 4.2.4 on 2024-06-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(default='Image/None/Noimf.jpg', upload_to='Image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.gearcategory')),
            ],
        ),
    ]
